	
all:
	  unibeam article.mrk article.tex
	  pdflatex article
	  bibtex article
	  pdflatex article
	  pdflatex article
	  mupdf article.pdf 



clean:
	   rm *.out *.bbl *.aux *.dvi *.pdf *.blg *.log 


